### ISSUE TITLE
Using go-logging causes go vet errors

### ISSUE THREAD

**Issue by marcin-ptaszynski** [hhkbp2/go-logging#1]
Hi there and thanks for sharing this library.

Running ``go vet`` on code that is using this ``go-logging`` causes errors. It seems that ``go vet`` [is trying to enforce convention on all Print(f) like functions/methods](https://godoc.org/golang.org/x/tools/cmd/vet#hdr-Printf_family).

Current workaround for me is to run ``Log`` method directly.

**Comment by hhkbp2** [comment]
Hi, sorry that I didn't notice this issue because I didn't use ```go vet```. It should be all right for the calling code to pass ```go vet``` if these methods
```go
Fatal()
Error()
Warn()
Info()
Debug()
```
are to be given aliases as
```go
Fatalf()
Errorf()
Warnf()
Infof()
Debugf()
```
and application codes call these alias methods instead.
Please let me know if you have any better idea. We could modify the source code to fix this issue after the discussion.

**Comment by hhkbp2** [comment]
Hi @marcin-ptaszynski ,

I have changed the method names as what my previous comment said(instead of adding aliases), and have run ```go tool vet``` to confirm no error of the Print(f) convention is triggered.

This issue should be fixed now. Please let me know if there is any problem of the latest code.

**Comment by marcin-ptaszynski** [comment]
Hi @hhkbp2,

Thanks for changing that. I apologize for the delay.

If modifying Logger interface is not a problem at this stage, I've extended interface in this PR hhkbp2/go-logging#2

This covers the case when you want to use default format for object, like
```go
result, err := doSth()
if err != nil {
	logger.Fatal(err)
}
```
Previously, You'd have to do it like this
```go
logger.Fatal(err.Error())
```
or 
```go
logger.Fatal(fmt.Sprint(err))
```

**Comment by hhkbp2** [comment]
@marcin-ptaszynski 
It's much better to has these extended interfaces. The PR has been merged without any change. Well done!

**Comment by marcin-ptaszynski** [comment]
Thanks!
