### ISSUE TITLE
How May I use Multi Write file to log in console as well as file

### ISSUE THREAD

**Issue by DineshGuptaa** [hhkbp2/go-logging#11]
Hello,
Please let me know how may I use Multi Write file to log in console as well as file. One more thing How may I configure package level log, Like same as Apache log4j. 

Regards,
Dinesh

**Comment by hhkbp2** [comment]
Hi @DineshGuptaa ,

A logger represents a log source, and a handler represents a log destination. If both file and standard output are needed to be logged for the same message, you could *construct a file handler and a stdout handler, then link them to the same logger*.

The package level `Logf/Fatalf/Errorf...` functions are linked to a predefined root logger, which could be accessed by *calling the `GetLogger()` function with a empty name `""`*. Any logger with non-empty dot-separated name such as "a.b" will be a child-logger of this root logger all along the hierarchy tree. Any log message logged by the the package level `Logf/Fatalf/Errorf...` will be propagated by root logger to those child-loggers all along the hierarchy tree.

**Comment by DineshGuptaa** [comment]
Hello hhkpb2,

Thanks for quick response.
I will try the same and if I face any issue will contact again. If you do the same as part of the document will help all the users.
Now closing.

Thanks

**Comment by hhkbp2** [comment]
Hi @DineshGuptaa ,

The design of `go-logging` comes from Python `logging` package, so as its usage and interfaces. The documentation of Python `logging` applies to `go-logging` as well. So I thought those Python docs are good enough and omitted to write duplicated docs for `go-logging`. 

If you have any usage question, the Python docs is a good reference. Any issue/question is also welcome to be raised here.
