### ISSUE TITLE
Local time instead of UTC for asctime

### ISSUE THREAD

**Issue by aishwaryaprabhat** [hhkbp2/go-logging#21]
Is there a way to log local time instead of UTC when defining "%(asctime)s" in the format when using config.yml?

**Comment by aishwaryaprabhat** [comment]
I figured that since I was using Docker to run my app, I just set the "TZ" environment variable according to the timezone I needed in my Dockerfile. That helped to fix the issue :)

**Comment by hhkbp2** [comment]
@aishwaryaprabhat The source codes use `time.Now()` to get the current time in local time zone. Usually it's what we need for log messages, to record something happens in current place and current time.
