### ISSUE TITLE
Option of a channel in TimedRotatingFileHandler

### ISSUE THREAD

**Issue by smaheshs** [hhkbp2/go-logging#22]
Hi,

Based on what I have gone through there is no option to provide a channel size for a timed rotating file handler.

Please let me know if my analysis is wrong and also if there are plans to implement channel for timed rotating file handler also.

Thanks.

**Comment by hhkbp2** [comment]
Hi,

You are right. `TimedRotatingFileHandler` doesn't have a internal goroutine to write log messages into file.

Following the implementation of Python `logging`, previously all handlers are implemented without internal goroutine as in `logging`. Later my teammate  discovered that the blocking wait on the log message writing was a big issue to our application in term of delay. Then I added an internal goroutine into the `RotatingFileHandler` implementation.

Do you get into a similar situation when using `TimedRotatingFileHandler`? I don't have a plan to make all handlers into goroutine impl for now. But we could do that to solve some issue if necessary.

**Comment by smaheshs** [comment]
Thanks for the response.

The issue I foresee is the same, i.e. delay due to blocking wait while writing the logs to a file.

Planning analytics where multiple modules will write to a file (one file for every 1 hour - which will be further processed by another system) and without a go routine performance may take a hit and if TimedRotatingFileHandler can have a go routine it would really help me here.

**Comment by hhkbp2** [comment]
Maybe I could try to find some time to make the goroutine impl recently. Then it would be helpful if you could do some measurement and confirm the impl could reach your requirement. And it's always welcome if you feel like making some PR to contribute any enhancement code or measurement.

**Comment by hhkbp2** [comment]
@smaheshs I added internal goroutine impl and parameters for `TimedRotatingFileHandler`. It should the issue. Thanks!
