### ISSUE TITLE
When my process is running in background , logging is not happening to file.

### ISSUE THREAD

**Issue by cshivaprasad** [hhkbp2/go-logging#25]
go version go1.19.5 linux/amd64

logging ver : 0.3.6

OS env: Linux  (Cent OS)

logging is not updated to file, when ever I am running my application in background , like

"nohup _myapp_&"

I could not find any information in documentation to force logger to work in background also.

Any help in this regard is very much helpful.

Thanks in advance

**Comment by cshivaprasad** [comment]
Dear hhkbp2,

Thanks for your response.. 
below is my YAML 


formatters:

    f:

        format: "%(asctime)s %(levelname)s (%(filename)s:%(funcname)s:%(lineno)d) %(message)s"

        datefmt: "%Y-%m-%d %H:%M:%S.%3n"

    aaaF:

        format: "%(message)s"

        datefmt: "%Y-%m-%d %H:%M:%S.%3n"

handlers:

    h:

        class: RotatingFileHandler

        filepath: "./logs/ABG.log"

        mode: O_APPEND

        bufferSize: 0

        # 30 * 1000 ms -> 30 seconds

        bufferFlushTime: 30000

        inputChanSize: 1

        # 100 * 1024 * 1024 -> 100M

        maxBytes: 104857600

        backupCount: 9

        formatter: f

loggers:

    main:

        level: DEBUG

        handlers: [h]

    core:

        level: DEBUG

        handlers: [h]

    util:

        level: DEBUG

        handlers: [h]

    svc:

        level: DEBUG

        handlers: [h]

**Comment by hhkbp2** [comment]
Hi @cshivaprasad ,

You configuration seems to be ok to output log message to file soon. The logging facility should work whether or not the process is running in background.

There is a `Close()` function in `Handler` interface. You could call it for any handler to force one log message flush when debugging. After calling `Close`, this handler is destroyed so you have to remove it from the attached logger if you still want to use this logger later.

**Comment by hhkbp2** [comment]
Hi @cshivaprasad, It's been a while. I'm gonna close this issue if there is no further update. You could reopen it or create a new issue if you have further question on this. Thanks.
