### ISSUE TITLE
go get error

### ISSUE THREAD

**Issue by fooevr** [hhkbp2/go-logging#6]
# go get error, report:
go get github.com/hhkbp2/go-logging
cd C:\GoPath\src\git.apache.org\thrift.git; git pull --ff-only
There is no tracking information for the current branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.

    git pull <remote> <branch>

If you wish to set tracking information for this branch you can do so with:

    git branch --set-upstream-to=origin/<branch> master

package git.apache.org/thrift.git/lib/go/thrift: exit status 1

**Comment by hhkbp2** [comment]
It looks like an issue when downloading thrift using `go get`.
I have removed the thrift handler from the branch master, since it's rarely used. This issue should be gone.
