### ISSUE TITLE
Incorrect RotatingFileHandler closing

### ISSUE THREAD

**Issue by fabregas** [hhkbp2/go-logging#8]
In `RotatingFileHandler.Close()` when `inputChanSize > 0` 1 sending to `exitChan`.
`RotatingFileHandler.loop()` receives 1 from `exitChan` and returns.
In this case some log records can be ignored in `inputChan` channel.

This issue sometimes catches by the test:
--- FAIL: TestRotatingFileHandler_AppendWithoutBackup (0.00s)
        Error Trace:    handler_rotating_file_test.go:89
	Error:      	Not equal:
	            	expected: 0x3a98
	            	actual: 0x3a34

**Comment by hhkbp2** [comment]
@fabregas Well done! The PR is merged.
